/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

/* Table schema:
CREATE TABLE kv_store_218684af (
  key TEXT NOT NULL PRIMARY KEY,
  value JSONB NOT NULL
);
*/

// View at https://supabase.com/dashboard/project/sdyqpwfhqsohivtzjkff/database/tables

// This file provides a simple key-value interface for storing Figma Make data. It should be adequate for most small-scale use cases.
import { createClient } from "jsr:@supabase/supabase-js@2.49.8";

// Singleton client — created once per Deno isolate, reused across all requests.
// Avoids the overhead of creating a new client (and HTTP connection) on every KV call.
const _supabase = createClient(
  Deno.env.get("SUPABASE_URL")!,
  Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,
);

// Set stores a key-value pair in the database.
export const set = async (key: string, value: any): Promise<void> => {
  const { error } = await _supabase.from("kv_store_218684af").upsert({ key, value });
  if (error) {
    throw new Error(error.message);
  }
};

// Get retrieves a key-value pair from the database.
export const get = async (key: string): Promise<any> => {
  const { data, error } = await _supabase.from("kv_store_218684af").select("value").eq("key", key).maybeSingle();
  if (error) {
    throw new Error(error.message);
  }
  return data?.value;
};

// Delete deletes a key-value pair from the database.
export const del = async (key: string): Promise<void> => {
  const { error } = await _supabase.from("kv_store_218684af").delete().eq("key", key);
  if (error) {
    throw new Error(error.message);
  }
};

// Sets multiple key-value pairs in the database.
export const mset = async (keys: string[], values: any[]): Promise<void> => {
  const { error } = await _supabase.from("kv_store_218684af").upsert(keys.map((k, i) => ({ key: k, value: values[i] })));
  if (error) {
    throw new Error(error.message);
  }
};

// Gets multiple key-value pairs in a single query.
// Returns values in the same order as the input keys; null for missing keys.
export const mget = async (keys: string[]): Promise<(any | null)[]> => {
  if (keys.length === 0) return [];
  const { data, error } = await _supabase
    .from("kv_store_218684af")
    .select("key, value")
    .in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
  const map = new Map<string, any>((data ?? []).map((d) => [d.key, d.value]));
  return keys.map((k) => map.get(k) ?? null);
};

// Deletes multiple key-value pairs from the database.
export const mdel = async (keys: string[]): Promise<void> => {
  const { error } = await _supabase.from("kv_store_218684af").delete().in("key", keys);
  if (error) {
    throw new Error(error.message);
  }
};

// Search for key-value pairs by prefix.
export const getByPrefix = async (prefix: string): Promise<any[]> => {
  const { data, error } = await _supabase
    .from("kv_store_218684af")
    .select("key, value")
    .like("key", prefix + "%");
  if (error) {
    throw new Error(error.message);
  }
  return (data ?? []).map((d) => d.value);
};
